package com.theundertaker11.GeneticsReborn.api.capability.genes;

public enum EnumGenes{
	DRAGONS_BREATH,
	EAT_GRASS,
	EMERALD_HEART,
	ENDER_DRAGON_HEALTH,
	FIRE_PROOF,
	FLY,
	JUMP_BOOST,
	MILKY,
	MORE_HEARTS,
	NIGHT_VISION,
	NO_FALL_DAMAGE,
	POISON_PROOF,
	RESISTANCE,
	SAVE_INVENTORY,
	SCARE_CREEPERS,
	SHOOT_FIREBALLS,
	SLIMY,
	SPEED,
	TELEPORTER,
	WATER_BREATHING,
	WOOLY,
	WITHER_HIT,
	WITHER_PROOF;
}